version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "npm"
  directory: "/src"
  schedule:
    interval: "daily" 
  target-branch: "main" 
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily" 
  target-branch: "main" 
  allow:
  - dependency-type: direct
  - dependency-type: production # check only dependencies, which are going to the compiled app, not supporting tools like @vue-cli
